language: python
python: "3.4"

install:
  - "pip install pep8"
  - "pip install coveralls"

before_script: "pep8 . --ignore=W293,E501"

script:
  - coverage run -m unittest discover

after_success:
  coveralls